apiVersion: v1
kind: Service
metadata: 
  name: lb-shopfront
spec:
  type: LoadBalancer
  selector:
    tag: t-shopfront
  ports:
  - name: port-lb-shopfront
    protocol: TCP
    port: 8080
    targetPort: 8010